### ISSUE TITLE
Block consumption limit is unrealistic for long filters

### ISSUE THREAD

**Issue by bjorksteinsson** [pothosware/pothos-library#93]
Pothos.Block.consume: FIRFilter0[0] overconsumed 8192 bytes, 1600 available

**Comment by guruofquality** [comment]
I think this is the bug: const auto N = std::min((inPort->elements()-(K-1))/M, outPort->elements()/L);

The number of taps are larger than the number of elements. The subtraction resulting in a huge number and output elements won the std::min batte. I should be checking this condition and setting the input reserve in the FIR block

**Comment by guruofquality** [comment]
candidate fix is on the master, we should have been bounds checking anyway: https://github.com/pothosware/pothos/commit/8157bc6d465f16f2e6a55fdf61eba9f12e047c7b

**Comment by bjorksteinsson** [comment]
Try a very long filter now. (>10000 taps)

Framework Topology Connect Error: Pothos::Topology::commit(): Framework Topology Connect Error: FIRDesigner0.activate(): Exception: Net Exception: Message too long

I suppose 10K taps pushes a limit of reasonableness.

**Comment by guruofquality** [comment]
Well, there is an open issue to handle fragmentation for very large data chunks: https://github.com/pothosware/pothos-blocks/issues/7

So, it can be made to work, but yea, too many taps. Once we get the taps to the block, there may be a be a second problem of insufficient buffering. Although, I think it might accumulate into a larger buffer based on the reserve requirement -- and actually work...

**Comment by guruofquality** [comment]
aha, I knew I had made a pool somewhere:
https://github.com/pothosware/pothos-library/blob/master/lib/Framework/BufferAccumulator.cpp#L11

And this is where the copy happens when contiguous buffer is not sufficient: https://github.com/pothosware/pothos-library/blob/master/lib/Framework/BufferAccumulator.cpp#L186

should be ok -- going to close this issue, since the problem should now just be in the network block for the gigantic serialized taps message
